# Generated by Django 4.2.28 on 2026-04-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_whitelistemail_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/alumni/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/students/'),
        ),
    ]
