# Generated by Django 4.2.28 on 2026-04-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alumniprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/alumni/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/students/'),
        ),
    ]
