# Generated by Django 4.2.28 on 2026-04-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_alumniprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='is_mentor_available',
            field=models.BooleanField(default=False),
        ),
    ]
