# Generated by Django 4.2.28 on 2026-04-17 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorshiprequest',
            unique_together={('student', 'mentor', 'status')},
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('platform', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams')], max_length=20)),
                ('meeting_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_session', to='mentorship.mentorshiprequest')),
            ],
        ),
    ]
